images/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('images/<str:img_name>/', views.image, name='image'),
    path('myimages/', views.myimages, name='myimages'),
    path('myimages/<str:imagename>/', views.imageedit, name='imageedit'),
    path('myimages/<str:imagename>/addrectangle/', views.addrectangle, name='addrectangle'),
    path('myimages/delrectangel/<int:recid>', views.delrectangle, name='delrectangle')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('images.urls', 'images'), namespace='images')),
    path('admin/', admin.site.urls),
    path('accounts/', admin.site.urls)
]

images/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Image(models.Model):
    name = models.CharField(max_length=200, unique=True)
    height = models.IntegerField(default=0)
    width = models.IntegerField(default=0)
    authors = models.ManyToManyField(User, related_name='authors')
    publication_date = models.DateTimeField(auto_now_add=True)
    tags = models.CharField(max_length=500, default='')
    def __str__(self):
        return self.name
    
    def containstag(self, tag):
        return tag in self.tags.split()
    
    
class Rectangle(models.Model):
    picture = models.ForeignKey(Image, on_delete=models.CASCADE, related_name='rectangles')
    height = models.IntegerField(default=0)
    width = models.IntegerField(default=0)
    color = models.CharField(max_length=100)
    x = models.IntegerField(default=0)
    y = models.IntegerField(default=0)
    

images/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from .models import Image
from .models import Rectangle

def index(request):
    class thumbnail:
        def __init__(self, image):
            self.name = image.name
            self.rectangles = image.rectangles.all()
            for rec in self.rectangles:
                rec.x = rec.x / image.width * 100
                rec.y = rec.y / image.height * 100
                rec.width = rec.width / image.width * 100
                rec.height = rec.height / image.height * 100
            
    params = request.GET.dict()
    page_order = params['order'] if 'order' in params else ''
    page_number = params['page'] if 'page' in params else 1
    if 'tag' in request.POST:
        page_tag = request.POST['tag']
    else:
        page_tag = params['tag'] if 'tag' in params else ''
    print(params)
    
    images_list = Image.objects.all()
    if page_order == 'desc':
        images_list = images_list.order_by('-publication_date')
    elif page_order == 'asc':
        images_list = images_list.order_by('publication_date')
    
    if page_tag != '':
        for image in images_list:
            if not image.containstag(page_tag):
                images_list = images_list.exclude(name=image.name)

    thumbnails = [thumbnail(image) for image in images_list]
    paginator = Paginator(thumbnails, 2)
        
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj,
               'order': page_order,
               'tag': page_tag}
    return render(request, 'images/paginator.html', context)

def image(request, img_name):
    image = Image.objects.get(name=img_name)
    rectangles = image.rectangles.all()
    context = {'image': image,
               'rectangles': rectangles}
    return render(request, 'images/image.html', context)

@login_required
def myimages(request):
    user = request.user
    user_images = Image.objects.filter(authors=user)
    context = {'images_list': user_images, 'user' : user}
    return render(request, 'images/myimages.html', context)

@login_required
def imageedit(request, imagename):
    image = Image.objects.get(name=imagename)
    user = request.user
    rectangles = image.rectangles.all()
    context = {'image': image,
               'gooduser' : image.authors.filter(username=user.username),
               'rectangles': rectangles}
    return render(request,'images/imageedit.html', context)

@login_required
def addrectangle(request, imagename):
    image = Image.objects.get(name=imagename)
    user = request.user
    
    if image.authors.filter(username=user.username).exists():
        rec = Rectangle(picture=image, height=int(request.POST['height']), width=int(request.POST['width']), color=request.POST['color'], x=int(request.POST['x']), y=int(request.POST['y']))
        rec.save()
    return HttpResponseRedirect('/myimages/' + imagename + '/')

@login_required
def delrectangle(request, recid):
    user = request.user
    rec = Rectangle.objects.get(id=recid)
    image = rec.picture
    if image.authors.filter(username=user.username).exists():
        rec.delete()
    return HttpResponseRedirect('/myimages/' + image.name + '/')

images/templates/images/image.html
<a href='/accounts/'>Manage account</a>
<a href="/">Return to images list</a>
<h1>{{ image.name }}</h1>
<svg width={{image.width}} height={{image.height}} viewBox="0 0 {{image.width}} {{image.height}}" version="1.1" xmlns="http://www.w3.org/2000/svg">
    {% for rectangle in rectangles %}
        <rect x="{{rectangle.x}}" y="{{rectangle.y}}" width="{{rectangle.width}}" height="{{rectangle.height}}" fill="{{rectangle.color}}"></rect>
    {% endfor %}
</svg>

images/templates/images/imageedit.html
<a href='/accounts/'>Manage account</a>
<a href="/myimages/">My images</a>
<a href="/">Return to all images list</a>
{% if gooduser %}
    <h1>{{ image.name }}</h1>
    <svg width={{image.width}} height={{image.height}} viewBox="0 0 {{image.width}} {{image.height}}" version="1.1" xmlns="http://www.w3.org/2000/svg">
        {% for rectangle in rectangles %}
            <rect x="{{rectangle.x}}" y="{{rectangle.y}}" width="{{rectangle.width}}" height="{{rectangle.height}}" fill="{{rectangle.color}}"></rect>
        {% endfor %}
    </svg>
    <h2>Specs</h2>
    <h3>Size</h3>
    <p>{{ image.width }} x {{ image.height }}</p>
    <h3>Rectangles</h3>
    <table style="width:100%">
        <tr>
            <th>x</th>
            <th>y</th>
            <th>width</th>
            <th>height</th>
            <th>color</th>
            <th>action</th>
        </tr>
        {% for rectangle in rectangles %}
        <tr>
            <td align="center">{{ rectangle.x }}</td>
            <td align="center">{{ rectangle.y }}</td>
            <td align="center">{{ rectangle.width }}</td>
            <td align="center">{{ rectangle.height }}</td>
            <td align="center">{{ rectangle.color }}</td>
            <td align="center"><a href="{% url 'images:delrectangle' rectangle.id %}">Delete</a></td>
        </tr>
        {% endfor %}
      </table>

    <h3>Add new rectangle</h3>
    <form action="{% url 'images:addrectangle' image.name %}" method="post">
        {% csrf_token %}
        <label for="x">X:</label>
        <input type="number" name="x" id="x" required>
        <label for="y">Y:</label>
        <input type="number" name="y" id="y" required>
        <label for="width">Width:</label>
        <input type="number" name="width" id="width" required>
        <label for="height">Height:</label>
        <input type="number" name="height" id="height" required>
        <label for="color">Color:</label>
        <input type="text" name="color" id="color" required>
        <input type="submit" value="Add rectangle">
    </form>
{% else %}
    <p>You are not an author of image {{image.name}}.</p>
{% endif %}

images/templates/images/index.html
<a href='/accounts/'>Manage account</a>
<a href="/myimages/">My images</a>
{% if images_list %}
    <h2>All images</h2>
    <ul>
    {% for image in images_list %}
        <li><a href="/images/{{ image.name }}/">{{ image.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No images are available.</p>
{% endif %}

images/templates/images/myimages.html
<a href='/accounts/'>Manage account</a>
<a href="/">Return to images list</a>
{% if images_list %}
    <h2>Your images, {{user.username}}</h2>
    <ul>
    {% for image in images_list %}
        <li><a href="{{ image.name }}/">{{ image.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>You do not have any image.</p>
{% endif %}

images/templates/images/paginator.html
<a href='/accounts/'>Manage account</a>
<a href="/myimages/">My images</a>
<br>

<h1>All images</h1>
<a href="?page=1&order=asc&tag={{tag}}">Sort from oldest</a>
<a href="?page=1&order=desc&tag={{tag}}">Sort from newest</a>
<br>
<form action="{% url 'images:index' %}" method="post">
    {% csrf_token %}
    <label for="tag">Filter by tag:</label>
    <input type="text" name="tag" id="tag">
    <input type="submit" value="Filter (clear if empty)">
</form>
{% if tag %}
    <p>Filtering by tag: {{tag}}</p>
{% endif %}
{% for image in page_obj %}
    <a href="/images/{{ image.name }}/">
        <svg width=100 height=100 viewBox="0 0 100 100" version="1.1" xmlns="http://www.w3.org/2000/svg">
            {% for rectangle in image.rectangles %}
                <rect x="{{rectangle.x}}" y="{{rectangle.y}}" width="{{rectangle.width}}" height="{{rectangle.height}}" fill="{{rectangle.color}}"></rect>
            {% endfor %}
        </svg>
        <p>{{image.name}}</p>
    </a>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1&order={{order}}&tag={{tag}}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}&order={{order}}&tag={{tag}}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&order={{order}}&tag={{tag}}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}&order={{order}}&tag={{tag}}">last &raquo;</a>
        {% endif %}
    </span>
</div>